#!/usr/bin/env node

const request = require('request-promise-native');
const { sendNotification } = require('./notifications');

function beep() {
    process.stdout.write('\x07');
}

function logCourse(course) {
    const time = new Date().toLocaleTimeString('en-US', {
        hour12: false,
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit'
    });

    console.log(`[${time}] ${course.code}-${course.section} (${course.status}): ${course.openSeats} open seats`);
}

async function checkCourse(courseNumber, quarter) {
    const response = await request({
        uri: 'https://pisa.ucsc.edu/class_search/index.php',
        method: 'POST',
        form: {
            action: 'detail',
            'class_data[:CLASS_NBR]': courseNumber,
            'class_data[:STRM]': quarter
        }
    });

    const nameMatch = response.match(/<h2 style="margin:0px;">\s*(.+?) - (\d+)(?:&nbsp;|\s)*(.+?)\s*<\/h2>/);
    const infoMatch = response.match(/<dt>Status<\/dt><dd><img src=".+?" alt="(.+?)" .+?<\/dd>\s*<dt>Available Seats<\/dt><dd>(\d+)<\/span><\/dd>/);

    const course = {
        code: nameMatch[1],
        section: nameMatch[2],
        title: nameMatch[3],
        status: infoMatch[1],
        openSeats: infoMatch[2]
    };

    logCourse(course);

    if (course.openSeats !== '0') {
        beep();
        sendNotification(`${course.code}-${course.section} has ${course.openSeats} open seats`);
    }
}

const interval = parseInt(process.argv[2]);
console.log(`Checking for course updates every ${interval} seconds`);

setInterval(checkCourse, interval * 1000, 63973, 2202);
